name: Plan terraform

on:
  pull_request:
      branches: [ "main" ]
      types:
        - opened

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: 'eu-west-2'

      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: init Terraform
        run: terraform init -backend-config="./state.config"  


      - id: plan
        run: terraform plan -out .planfile

      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ github.token }}
          planfile: .planfile
