name: Plan terraform

on:
  push:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: 'eu-west-2'

      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: init Terraform
        run: terraform init -backend-config="./state.config"  

      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}